site_name: Vortex | Linux ACL Management System
theme:
  name: readthedocs
  pygments_style: dracula
  icon: heroicons:cube
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - content.action.view

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
